---
- name: Check if application path exists
  ansible.builtin.stat:
    path: "{{ lens_installation_path }}"
  register: app_exists

- name: Download the application installation file ({{ ansible_distribution }})
  ansible.builtin.get_url:
    url: "{{ lens_package_deb_url }}"
    dest: "{{ lenst_deb_package_destination }}"
  when: not app_exists.stat.exists

- name: Install the application .deb package ({{ ansible_distribution }})
  ansible.builtin.apt:
    deb: "{{ lenst_deb_package_destination }}"
  when: not app_exists.stat.exists

- name: Remove application .deb package ({{ ansible_distribution }})
  ansible.builtin.file:
    path: "{{ dotnet_deb_package_destination }}"
    state: absent
  when: not app_exists.stat.exists
