---
- name: Install the application dependencies ({{ ansible_distribution }})
  ansible.builtin.apt:
    pkg: "{{ docker_dependencies }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Import the APT repo key ({{ ansible_distribution }})
  ansible.builtin.apt_key:
    url: "https://download.docker.com/linux/{{ distro }}/gpg"
    state: present

- name: Create the APT repository ({{ ansible_distribution }})
  ansible.builtin.apt_repository:
    repo: "deb https://download.docker.com/linux/{{ distro }} {{ lsb_release }} stable"
    # dest: /etc/apt/trusted.gpg.d/docker.gpg
    state: present

- name: Install the application package ({{ ansible_distribution }})
  ansible.builtin.apt:
    pkg: "{{ docker_packages_names }}"
    state: present
    update_cache: yes

- name: Add 'docker' group.
  ansible.builtin.group:
    name: "{{ docker_group }}"
    state: present

- name: Add user to Docker group.
  ansible.builtin.user:
    name: "{{ default_username }}"
    groups:
      - "{{ docker_group }}"
    append: yes

- name: Ensure Docker service is up and running.
  ansible.builtin.service:
    name: "{{ docker_service }}"
    state: started
    enabled: yes
