---
- name: Install the application dependencies ({{ ansible_distribution }})
  ansible.builtin.apt:
    pkg: "{{ kubectl_dependencies }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Import the APT repo key ({{ ansible_distribution }})
  ansible.builtin.apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Create the APT repository ({{ ansible_distribution }})
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main"
    # dest: /etc/apt/trusted.gpg.d/kubernetes-archive-keyring.gpg
    state: present

- name: Install the application package ({{ ansible_distribution }})
  ansible.builtin.apt:
    pkg: "{{ kubectl_package }}"
    state: present
    update_cache: yes
