---
- name: Provision developer workstation
  hosts: all
  become: true

  vars_files:
    - vars/defaults.yml
    - vars/docker.yml
    - vars/kubectl.yml
    - vars/azure_cli.yml

  roles:
    - role: docker
    - role: kubectl
    - role: microsoft/azure/cli
    - role: microsoft/ide/vscode
