---
- name: Provision developer workstation
  hosts: all
  become: true

  vars_files:
    - defaults/main.yml

  roles:
    - role: docker
    - role: kubectl
    - role: lens
    - role: microsoft/dotnet
    - role: microsoft/azure_cli
    - role: microsoft/vscode
