---
- name: Install work workstation
  hosts: all
  become: true

  vars_files:
    - vars/defaults.yml
    - vars/docker.yml
    - vars/azure_cli.yml

  roles:
    - role: docker
    - role: azure/cli
