---
- name: Update apt-get repo and cache
  ansible.builtin.apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

- name: Upgrade all apt packages
  ansible.builtin.apt:
    upgrade: dist
    force_apt_get: yes

- name: Install system's pre-requisites
  ansible.builtin.apt:
    pkg: "{{ system_pre_requisites }}"
    state: latest
    